config/routes.rb
Rails.application.routes.draw do
  root to: 'setlists#index'
  resources :setlists
  resources :songs

  get :add_songs, controller: 'setlists', :as => 'add_songs'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/setlist.rb
class Setlist < ApplicationRecord
  after_create_commit { broadcast_prepend_later_to 'setlists' }
  after_update_commit { broadcast_replace_later_to 'setlists' }
  after_destroy_commit { broadcast_remove_to 'setlists' }
  has_many :songs
  validates :title, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  after_create_commit { broadcast_prepend_later_to 'songs' }
  after_update_commit { broadcast_replace_later_to 'songs' }
  after_destroy_commit { broadcast_remove_to 'songs' }
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/setlists_controller.rb
class SetlistsController < ApplicationController
  before_action :set_setlist, only: %i[ show edit update destroy ]

  # GET /setlists or /setlists.json
  def index
    @setlists = Setlist.all.order(created_at: :desc)
    @setlist = Setlist.new
    @song = Song.new
    @songs = Song.all
  end

  # GET /setlists/1 or /setlists/1.json
  def show
  end

  # GET /setlists/new
  def new
    @setlist = Setlist.new
  end

  # GET /setlists/1/edit
  def edit
    @songs = Song.all.order(created_at: :desc)
  end

  def add_songs
    format.turbo_stream { render turbo_stream: turbo_stream.replace(@setlist_songs, partial: 'posts/form', locals: { setlist_songs: @setlist_songs }) }
  end


  # POST /setlists or /setlists.json
  def create
    @setlist = Setlist.new(setlist_params)
    respond_to do |format|
      if params[:create_song] && @setlist.save
        format.html { redirect_to setlists_path, notice: "Setlist was successfully created." }
        format.json { render :show, status: :created, location: setlists_path }
      elsif params[:create_song]
        Setlist.find(@setlist.id).update(:songs_id => params[:songs_id])
        format.html { render :index }
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@song, partial: 'posts/songs', locals: { song: @song }) }
      elsif @setlist.save
        format.html { redirect_to setlists_path, notice: "Setlist was successfully created." }
        format.json { render :show, status: :created, location: setlists_path }
      else
        format.html { render :index }
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@setlist, partial: 'posts/form', locals: { setlist: @setlist }) }
        # I think we want to replace the song turbo_stream here as well - This should stop displaying the song index before a setlist is made
      end
    end
  end

  # PATCH/PUT /setlists/1 or /setlists/1.json
  def update
    binding.pry
    respond_to do |format|
      if @setlist.update(setlist_params)
        format.html { redirect_to @setlist, notice: "Setlist was successfully updated." }
        format.json { render :show, status: :ok, location: @setlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @setlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setlists/1 or /setlists/1.json
  def destroy
    @setlist.destroy
    respond_to do |format|
      format.html { redirect_to setlists_url, notice: "Setlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setlist
      @setlist = Setlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def setlist_params
      params.require(:setlist).permit(:title, :songs_id)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: %i[ show edit update destroy ]

  # GET /songs or /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :index }
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@song, partial: 'posts/form', locals: { song: @song }) }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/setlists_helper.rb
module SetlistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SetlistApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= turbo_include_tags %> 
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/setlists/_add_songs_form.html.erb
<%= turbo_frame_tag @setlists_songs do %>
<%= form_with(model: @setlist, id: dom_id(@setlist), url: add_songs_path) do |form| %>
    <div class="field">
    <%= form_tag add_songs_path do %>
      <%= form.label :songs_id, name: "new_setlist_song" %>
      <div class="flex">
        <div class="flex-1">
          <%= form.select @setlist.id, @songs.collect { |song| [song.title, song.id] }, {}, { class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" }%>
        </div>
        <div class="flex-2 pl-6 ">
          <%= form.submit "Add Song", class: 'py-2 px-8 mr-6 bg-blue-600 hover:bg-blue-700 focus:ring-blue-500 focus:ring-offset-blue-200 text-white w-full transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2  rounded-full' %>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
<% end %>

app/views/setlists/_edit_form.html.erb
<%= form_with(model: setlist, id: dom_id(setlist)) do |form| %>
  <% if setlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setlist.errors.count, "error") %> prohibited this setlist from being saved:</h2>

      <ul>
        <% setlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field block text-gray-700 text-sm font-bold mb-2">
    <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
    </div>

    <div class="field">
      <%= form.label :songs_id %>
      <%= form.select @setlist.id, @songs.collect { |song| [song.title, song.id] }, {}, { class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" }%>
    </div>
    <br/>
    <div class="actions">
      <%= form.submit class: 'py-4 px-6  bg-blue-600 hover:bg-blue-700 focus:ring-blue-500 focus:ring-offset-blue-200 text-white w-full transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2  rounded-full' %>
    </div>
    </div>
  </div>
<% end %>

app/views/setlists/_form.html.erb
<%= form_with(model: setlist, id: dom_id(setlist)) do |form| %>
  <% if setlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setlist.errors.count, "error") %> prohibited this setlist from being saved:</h2>

      <ul>
        <% setlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-gray-700 text-sm font-bold">
    <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
    </div>

      <%= render "setlists/add_songs_form" %>

    <table class="table p-4 bg-white shadow rounded-lg">
      <thead>
        <tr>
          <th class="setlist-songs border-b-2 p-4 dark:border-dark-5 whitespace-nowrap font-normal text-gray-900">
              <%= render 'show_setlist_songs' %> 
          </th>
        </tr>
      </thead>
    </table>


    <div class="actions">
      <%= form.submit class: 'py-4 px-6  bg-blue-600 hover:bg-blue-700 focus:ring-blue-500 focus:ring-offset-blue-200 text-white w-full transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2  rounded-full' %>
    </div>
    </div>
  </div>
<% end %>

app/views/setlists/_setlist.html.erb
<%= turbo_frame_tag dom_id(setlist) do %>
 <div class="setlist">
  <div><%= setlist.title %></div>

  <div class="mt-2">
    <%= link_to "Edit", edit_setlist_path(setlist) %>
    <br/>
    <br/>
  </div>
</div>
<% end %> 

app/views/setlists/_show_setlist_songs.html.erb
<div id="<%= dom_id(@songs)%>">
  <%= @songs %>
  </div>

<%
=begin%>
 <%= turbo_frame_tag "setlists_songs" do %>
  <%= @setlist_songs %>
<%end%> 
<%
=end%>

app/views/setlists/_songs.html.erb
<div class="flex">
  <div class="flex-1">
    <table class="table p-4 bg-white shadow rounded-lg">
      <thead>
        <tr>
          <th class="border-b-2 p-4 dark:border-dark-5 whitespace-nowrap font-normal text-gray-900">
            <%= turbo_frame_tag "songs" do %>
              <%= render @songs %>
            <% end %>
          </th>
        </tr>
      </thead>
    </table>
  </div>
</div>

app/views/setlists/edit.html.erb
<h1>Editing Setlist</h1>

<%= turbo_frame_tag dom_id(@setlist) do %>
  <div class="setlists">
    <%= render 'edit_form', setlist: @setlist %>
    <%= link_to "Cancel", @setlist %>
  </div>
<% end %>

app/views/setlists/home.html.erb
<h1>Create a setlist and share it with anybody!</h1>

app/views/setlists/index.html.erb
<%= turbo_stream_from "setlists" %>

<div class="flex">
  <div class="flex-1">
    <%= turbo_frame_tag "setlists_form" do %>
      <%= render "setlists/form", setlist: @setlist %>
    <% end %>
  </div>

  <div class="flex-1">
    <%= turbo_frame_tag "songs_form" do %>
      <%= render "songs/form", song: @song %>
    <% end %> 
  </div>
</div>

<div class="flex">
  <div class="flex-1">
    <table class="table p-4 bg-white shadow rounded-lg">
      <thead>
        <tr>
          <th class="border-b-2 p-4 dark:border-dark-5 whitespace-nowrap font-normal text-gray-900">
            <%= turbo_frame_tag "setlists" do %>
              <%= render @setlists %>
            <% end %>
          </th>
        </tr>
      </thead>
    </table>
  </div>


  <div class="flex-1">
    <table class="table p-4 bg-white shadow rounded-lg">
      <thead>
        <tr>
          <th class="border-b-2 p-4 dark:border-dark-5 whitespace-nowrap font-normal text-gray-900">
            <%= turbo_frame_tag "songs" do %>
              <%= render @songs %>
            <% end %>
          </th>
        </tr>
      </thead>
    </table>
  </div>
</div>

app/views/setlists/new.html.erb
<h1>New Setlist</h1>

<%= render 'form', setlist: @setlist %>

<%= link_to 'Back', setlists_path %>

app/views/setlists/show.html.erb
<p id="notice"><%= notice %></p>

<%= turbo_frame_tag dom_id(@setlist) do %>
  <%= render @setlist %>
<% end %>

<%= link_to 'Edit', edit_setlist_path(@setlist) %> |
<%= link_to 'Back', setlists_path %>

app/views/songs/_edit_form.html.erb
<%= form_with(model: song, id: dom_id(song)) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field block text-gray-700 text-sm font-bold mb-2">
    <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
    </div>

    <div class="field">
      <%= form.label :songs_id %>
      <%= form.text_field :songs_id, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
    </div>
    <br/>
    <div class="actions">
      <%= form.submit class: 'py-4 px-6  bg-blue-600 hover:bg-blue-700 focus:ring-blue-500 focus:ring-offset-blue-200 text-white w-full transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2  rounded-full' %>
    </div>
    </div>
  </div>
<% end %>

app/views/songs/_form.html.erb
<%= form_with(model: song) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/songs/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Songs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.url %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/_song.html.erb
<%= turbo_frame_tag dom_id(song) do %>
 <div class="song">
  <div><%= song.title %></div>

  <div class="mt-2">
    <%= link_to "Edit", edit_song_path(song) %>
    <br/>
    <br/>
  </div>
</div>
<% end %> 

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%
=begin%>
 <%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %> 
<%
=end%>

<%= turbo_frame_tag dom_id(@song) do %>
  <div class="songs">
    <%= render 'edit_form', song: @song %>
    <%= link_to "Cancel", @song %>
  </div>
<% end %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Songs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.url %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<%= turbo_frame_tag dom_id(@song) do %>
  <%= render @song %>
<% end %>

<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @song.url %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>